colors:
  NEJM_set: ["#0172B6", "#E18727", "#BD3C29"]
project:
  my_proj:
    my_dataset:
      geneder:
        male:   "{{ colors.NEJM_set[0] }}" # "#0172B6"
        female: "{{ colors.NEJM_set[2] }}" # "#BD3C29"
